version: "3"
services:
  app:
    build: ./app
    ports:
      - "5001:5000"
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"
    ports:
      - '3308:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: